# -*- coding: utf-8 -*-
"""app4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z0PZ12RMOZphd5rFoLvgS8CkbdA7LZ6o
"""

!pip install streamlit

import streamlit as st
import pickle
import numpy as np

!pip install pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app4.py

st.set_page_config(page_title="Bankruptcy Prediction", layout="centered")
st.title("📉 Bankruptcy Risk Prediction App")

industrial_risk = st.selectbox("Industrial Risk", [0, 0.5, 1])
management_risk = st.selectbox("Management Risk", [0, 0.5, 1])
financial_flexibility = st.selectbox("Financial Flexibility", [0, 0.5, 1])
credibility = st.selectbox("Credibility", [0, 0.5, 1])
competitiveness = st.selectbox("Competitiveness", [0, 0.5, 1])
operating_risk = st.selectbox("Operating Risk", [0, 0.5, 1])

features = np.array([[industrial_risk, management_risk, financial_flexibility,
                      credibility, competitiveness, operating_risk]])

scaled_features = scaler.transform(features)

if st.button("Predict Bankruptcy"):
    prediction = model.predict(scaled_features)[0]
    prob = model.predict_proba(scaled_features)[0][1]
    if prediction == 1:
        st.error(f"⚠️ High Risk: Likely Bankruptcy (Prob: {prob:.2f})")
    else:
        st.success(f"✅ Low Risk: No Bankruptcy (Prob: {prob:.2f})")

from google.colab import files
uploaded = files.upload()

from google.colab import files
uploaded = files.upload()

with open("bankruptcy_model.pkl", "rb") as f:
    model = pickle.load(f)

with open("scaler.pkl", "rb") as f:
    scaler = pickle.load(f)

from pyngrok import ngrok
import os

!pkill streamlit